version: "3.9"

services:
  code-server:
    image: codercom/code-server:latest
    restart: unless-stopped
    container_name: code-server
    ports:
      - "8080:8080"
      - "4000-4020:4000-4020"
    volumes:
      - /home/docker/coder/.local:/home/coder/.local
      - /home/docker/coder/.config:/home/coder/.config
      - /home/docker/coder/project:/home/coder/project
    user: "${UID}:${GID}"
    environment:
      - DOCKER_USER=${USER}
      - PASSWORD=@Badat120297
    networks:
      - infrastructure_default
    stdin_open: true
    tty: true
networks:
  infrastructure_default:
    external: true
