---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - PASSWORD=@Badat120297
      - SUDO_PASSWORD=@Badat120297
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /home/carem/server/coder/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
