services:
  postgres:
    container_name: postgresql_con
    image: postgres:16.4-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-datnguyen}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-datnguyen}
    volumes:
      - /home/icpro/docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    container_name: minio_con
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /home/icpro/docker/minio:/data
    environment:
      MINIO_ROOT_USER: datnguyen
      MINIO_ROOT_PASSWORD: datnguyen
    command: server --console-address ":9001" /data
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/icpro/docker/redis:/data
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
