services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 5000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: livestock
      MB_DB_PASS: 123abc
      MB_DB_HOST: postgres
    networks:
      - postgre-stack_default
      - metabase-net
    healthcheck:
      test: curl --fail -I http://localhost:5000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  metabase-net:
    driver: bridge
    name: metabase-net
  postgre-stack_default:
    external: true