version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /d/linux/minio:/data
    environment:
      MINIO_ROOT_USER: datnguyen
      MINIO_ROOT_PASSWORD: it@datnguyen@
      # MINIO_BROWSER_REDIRECT_URL: https://minio.cjlivestock.net
      MINIO_SERVER_URL: https://api.storage.cjvina.com
    command: server --console-address ":9001" /data
