version: "3.8"

services:
  postgres:
    container_name: postgres-sql-con
    image: postgres:16.4-bullseye
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-livestock}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123abc}
      PGDATA: /data/postgres
    volumes:
      - /mnt/d/linux/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: postgres-pgadmin-con
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-nguyentubadat833@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-it@datnguyen@}
    volumes:
      - /mnt/d/pgadmin:/var/lib/pgadmin
      -
    ports:
      - "${PGADMIN_PORT:-5050}:80"
