version: "3.8"

services:
  postgres:
    container_name: postgres-sql-con
    image: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-livestock}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123abc}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /mnt/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
