services:
  postgres:
    image: postgres:16.4-bullseye
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-datnguyen}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123abc}
    volumes:
      - /home/datnguyen/docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  pgadmin:
#    container_name: postgres-pgadmin-con
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-nguyentubadat833@gmail.com}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-it@datnguyen@}
#    volumes:
#      # - pgadmin-vol:/var/lib/pgadmin
#      - /d/linux/pgadmin/storage:/var/lib/pgadmin/storage
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"

# volumes:
#   pgadmin-vol:
#     name: pgadmin-vol
